apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: envoy-receiver
  labels:
    app.kubernetes.io/name: envoy-receiver
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
roleRef:
  kind: ClusterRole
  name: envoy-receiver
  apiGroup: rbac.authorization.k8s.io
